[build]
builder = "NIXPACKS"
buildCommand = "npm install --production"
nixpacks.nodejs.version = "18.x"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
maxRestarts = 3
restartDelay = "10s"

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_NODEJS_VERSION = "18" 